### PR TITLE
Add support for scenes.  Other fixes and improvements.

### PR DESCRIPTION
**Pull request by OleksandrBerchenko**
Resolving #7 .

### CODE REVIEW

**Comment by OleksandrBerchenko** [comment]
- Add scenes support (read the list of scenes and activate an individual scene)
- Expose whether the lights are reachable or not
- Fix crash in update_light_status when the light is not reachable
- Fix "time offline" value and expose it (actually "last seen" value in minutes)
- Make "on" always boolean (fix int/boolean mess)
- Expose original device type
- Set properties that don't exist for a particular device type to a reasonable default
- Minor refactoring

**Comment by tfriedel** [comment]
thanks for your work. I will try it out soon. 
did you see there are some tests in test_lightify.py. 
It requires some changes to your situation (names of lights and groups) and observing if the lights do what they should. 
this should be extended for scenes also.

**Comment by OleksandrBerchenko** [comment]
Thanks!  Looking into tests right now.

**Comment by OleksandrBerchenko** [comment]
I have added scenes to the tests.  Unfortunately, I'm not able to test RGB lights.

**Comment by OleksandrBerchenko** [comment]
More to come tomorrow.

**Comment by OleksandrBerchenko** [comment]
At the moment there is no way to detect that some light changed its name.  I will fix that.

Much worse: keys in public lightify.groups() dict are mutable names (not immutable indices like lightify.lights() with immutable addrs as keys).  Need to think how to deal with that.

**Comment by OleksandrBerchenko** [comment]
Also we need to handle a case when a light was deleted from gateway, but the library consumer keeps a link to the object.

**Comment by OleksandrBerchenko** [comment]
Well, I have decided to leave groups dict without changes (as well as scenes dict made by copying existing behavior of groups dict).  All objects in the dict are recreated after each update anyway (unlike lights where we keep original objects when possible), so probably nobody keeps links to the objects themselves.

**Comment by OleksandrBerchenko** [comment]
I really hoped to obtain battery level of switches (it's displayed in the application + according to https://github.com/noctarius/lightify-binary-protocol, lum value works as battery level for motion sensors), but without luck :(  I have two switches with different battery levels and both return exactly the same bytes.

**Comment by OleksandrBerchenko** [comment]
- Correctly handle light name change
- Mark properly a light that was deleted from gateway
- Ignore unsupported device actions
- When updating a group (onoff, lum, temp or rgb), set appropriate properties for all group lights
- Expose firmware version
- Don't expose uninitialized lights(), groups() and scenes()
- Remove Luminary class (finally)
- Implement other minor fixes and some refactoring
- Add missing and unify existing docstrings
- Follow a consistent code style and make pylint happy (where possible)

**Comment by OleksandrBerchenko** [comment]
Ooph...  That's all for now, I think.

Looking forward for your review.  Thanks!

**Comment by OleksandrBerchenko** [comment]
Well...  I have already started reworking Home Assistant integration part, so new changes may follow if needed.

Thanks!

**Review by tfriedel — APPROVED** [review]
seems fine

**Comment by tfriedel** [comment]
first of all, thanks again for your hard work! you improved this lib quite a bit. 
When I first tried to run the tests in my environment I experienced some problems due to this line
``` python
devicetype_raw = DeviceTypeRaw(devicetype_raw)  
```
I have lamps from three different manufacturers currently: osram lightify, ikea and innr. And these devicetypes that are listed don't cover all of them. For example one lamp has 128 as devicetype. 
You have to have reasonable fallbacks for the case your hardcoded ids don't cover a device. That's why
``` python
ID_TO_DEVICETYPE = defaultdict(lambda: DeviceType.LIGHT)
```
 maps any ID that is not in the dict to a light. 
I just removed the above line, since it doesn't matter if it's an int or an enum, when we look for it in the dict anyway. 
After this everything worked. I noticed that you fixed a bug with the groups. Very nice!
Scenes also worked for me. Well there's one bug in the gateway where it doesn't set some of the ikea lamps in a scene to the correct temeprature. But this is also with the original osram lightify app. Because of things like this I'm going to use home assistant scenes instead of the lightify scenes. 

I don't have the time to go through all your changes and am just going to trust that they are good. 
I can offer to test the lib with your modified home assistant lib when it's ready.

**Pull request merged**
