### PR TITLE
Use only bytes in build commands

### PR DESCRIPTION
**Pull request by deisi**
This commit makes sure, that only byte type objects are added with struct
obj. The old try and except was failing in newer python versions.

I've tested it with python3.5 and python3.6 and it seems to work. With python2.7 it doesn't, but I think that's not a problem.

### CODE REVIEW

**Comment by tfriedel** [comment]
thanks! I will test it soon with my home assistant installation and make a pull request there.

**Comment by deisi** [comment]
Okay, I'm also working on adding the group features there. :)

**Comment by deisi** [comment]
w8 before you make the pr to HA, because I just realized, it will be super handy to add an `on` member function to the `Group` class, because, then I can add the lightify groups with only very little code change to HA.

**Comment by deisi** [comment]
hmmm now I realized, when I would add everything that I need to the `Group` class directly, it would end up, beeing almost identical to the `Light` class....

**Comment by deisi** [comment]
okay, I think I made up my mined. I checked the hue implementation and there it is handled within HA itself, so I believe its best to follow this as a reference. Thus no further changes to python_lightify needed.

**Pull request merged**
