### PR TITLE
More fixes and some refactoring

### LINKED ISSUE #7: Ability to activate scenes
There is no functionality to activate a scene now.  According to https://github.com/noctarius/lightify-binary-protocol#packet_activate_scene there is a way to do so (though it's not really clear how to get a scene ID).

External Lightify API supports scenes already: https://docs.lightify-api.com/#d0237010-be9a-4994-a9bb-88aefa272c8a .

Thanks!

### PR DESCRIPTION
**Pull request by OleksandrBerchenko**
Thanks for the review of the previous PR!

1.  Oops...  I have totally missed that the list of device types may be incomplete and will evolve in the future.  I have reworked this piece of functionality - see my new changes.  I have also moved device type from `update_all_light_status` to `__init__` (it's an incompatible change, but hopefully nobody directly creates Light objects).

2. Several other minor improvements.

3. It seems you have lost your changes from https://github.com/tfriedel/python-lightify/commit/c9347b97b2979e86da8e2bab5a38c3c40647cbce

4. We can probably close https://github.com/tfriedel/python-lightify/issues/7

5. Some other changes may follow once I finished work on Home Assistant integration.  I will let you know.

Thanks!

### CODE REVIEW

**Comment by OleksandrBerchenko** [comment]
We need to track deleted groups/scenes, because Home Assistant keeps links and a deleted group is available until next HA restart.

**Comment by OleksandrBerchenko** [comment]
New device types:
31 - Contact Sensor
66 - Switch Mini

Also I have renamed generalized type MOTIONSENSOR to just SENSOR (to include Contact Sensor and possibly more sensors in the future).  It's a breaking change, but we have to do it to avoid confusion.

**Comment by OleksandrBerchenko** [comment]
You also mentioned "For example one lamp has 128 as devicetype" - shouldn't we also add them?  Is it fixed white, tunable white or RGB lamp?

**Comment by OleksandrBerchenko** [comment]
Draft version of HA integration is ready.  I plan to finish it in a few days - will keep you updated.

Small updates to python-lightify library may still follow till that time.

**Comment by rbdubz3** [comment]
I've been utilizing a version of this code with a home automation system called Indigo. I tested a recent version this repo and found an issue - seemed as if requests for changing the color temp of an RGBW Lightify Bulb wasn't working properly - esp. if color temp was a lower value (say < 2700K)

**Comment by OleksandrBerchenko** [comment]
@rbdubz3,

Thanks for your comment!

Well...  As far as I know, Osram Lightify Tunable White bulbs have a range 2700..6500 and Osram Lightify RGB bulbs have a range 1900..6500.  All unknown device types assumed to have 1900..6500.  At least, if you are using the latest version here (not merged into master yet).  The version in master still has a hardcoded 2700..6500 range for all devices.

So, could you please double check what version you are using?  And if your bulb supports color temperature < 1900, please report exact range and device type.

**Comment by rbdubz3** [comment]
@OleksandrBerchenko - will-do . Need to check later tonight. Most of my RGBW (A19/RT56/Colorstrip/BR30) seem to support color temp 1500-6500K. I will double-check the specs on any packaging I have. My only tunable-white has the range you mention - 2700-6500K .. 

BTW - would you prefer I open an 'Issue' ticket directly or just add comments for you?

**Comment by OleksandrBerchenko** [comment]
@rbdubz3, it's not my repo :)  Probably, a comment here would be enough.

Thanks!

**Comment by OleksandrBerchenko** [comment]
@rbdubz3, I used information from this spec: https://enlight.tech/wp-content/uploads/2016/12/osram-lightify-rgbw-smart-connected-lighting-product-information-bulletin2-english.pdf .  Unfortunately, my only RGB lamp died several months ago :(

**Comment by tfriedel** [comment]
yes we should. although I also think it's possible that these devicetype
IDs from other vendors might not have unique ones. it's not like there is a
registry where vendors go to and pick a unique ID, or is there?
the lamp that has this devicetype is this one:
https://www.ikea.com/de/de/catalog/products/10318263/
appears as

TRADFRI bulb E27 WS opal 980lm

It is tunable white. However, interestingly enough in the official osram
lightify app, you can only change it's brightness (the temperature slider
is deactivated). With homeassistant / python-lightify you can change it.


Am Di., 15. Jan. 2019 um 09:41 Uhr schrieb OleksandrBerchenko <
notifications@github.com>:

**Comment by tfriedel** [comment]
And Osram Smart+ Switch Mini has devicetype 66.

Am Di., 22. Jan. 2019 um 00:50 Uhr schrieb Thomas Friedel <
thomas.friedel@gmail.com>:

**Comment by rbdubz3** [comment]
@OleksandrBerchenko - you are correct - not sure how I got the 1500K in there.. However, the version I tested wouldn't push the RGBW bulbs below 2700K - or definitely wouldn't make it to 1900K

**Comment by OleksandrBerchenko** [comment]
@rbdubz3 Could you please test the newest version (it's already merged into master).

Thanks!

**Comment by OleksandrBerchenko** [comment]
@tfriedel Can you confirm that your Tradfri bulb reports (red, green, blue) as (1, 0, 0)?

Thanks!

**Comment by rbdubz3** [comment]
@OleksandrBerchenko - tested from master and it worked fine - sorry for the false alarm. 

@tfriedel - have some minor adds if interested. Basically I made small changes to allow control over logging output from the library - Class Lightify(....) .. adding a logging handler plus method to manipulate log-level. Lemme know and I can create an issue/PR/etc

**Comment by OleksandrBerchenko** [comment]
@rbdubz3 Thanks!

I have completely reworked device type handling, will make a new PR soon.  Just want to double check that Tradfri bulb reports (red, green, blue) as (1, 0, 0) (like any other device that doesn't support RGB).

**Comment by OleksandrBerchenko** [comment]
@tfriedel 
> although I also think it's possible that these devicetype IDs from other vendors might not have unique ones.

Probably you are right.  Also if the official Lightify app is not aware about its capabilities, it looks like they didn't add that ID to their internal database at all (and just assume that an unknown bulb is at least dimmable).

**Comment by rbdubz3** [comment]
A bit of a python newbie - would you expect this code to work for older 2.7.x versions of python? My setup with Indigo on Mac OS X uses 2.7. I get intermittent errors on the 'data = data.encode('cp437')'  987/990 lines of code

**Comment by OleksandrBerchenko** [comment]
@rbdubz3 I'm not sure it was ever planned to support Python 2.7.  Anyway, I will take a look: if it's an easy fix, I will do it.

**Comment by OleksandrBerchenko** [comment]
I have created a new PR: https://github.com/tfriedel/python-lightify/pull/11

@rbdubz3 Could you please test the new code in Python 2.7?  You can take it from https://github.com/OleksandrBerchenko/python-lightify.  Does it work without issues now?

Thanks!

**Comment by OleksandrBerchenko** [comment]
@tfriedel I would appreciate if you could test the new code with your Tradfri bulbs.  Thanks!

**Comment by tfriedel** [comment]
> 
> 
> @tfriedel Can you confirm that your Tradfri bulb reports (red, green, blue) as (1, 0, 0)?
> 
> Thanks!

yes, it reports as (1,0,0)

**Comment by rbdubz3** [comment]
@OleksandrBerchenko @tfriedel - have you guys ever had a Lightify Hub bite the dust? Not sure what happened and if it could be related to the latest code.. I finally got around to testing the latest in master. Set it up in my system - ran for a few minutes without issue - then I had to run an errand for about 30min. When I returned to my house it looked a bit like I had a power failure on a circuit - PS3/TV/Heater turned off. I don't think Hub is on the same circuit.. Anyhow - after noticing this potential electrical issue - tested any of my Lightify home automation integration and nothing works - even the Lightify App won't operate the bulbs anymore - all bulbs still show in the Lightify Mobile app, but they appear disconnected and unresponsive. I can still ping the Lightify Hub but it does nothing. I unplugged it for a bit and plugged it back in. Still nothing. 

Any tips on this one? I do have another Lightify Hub but I'd probably have to completely re-do my setup.

**Comment by OleksandrBerchenko** [comment]
Looks like a voltage spike.  The only thing that I can suggest is to disconnect both Hub and the bulbs for ~30 seconds and reconnect again.  Sometimes that helps electronic devices to resurrect.

**Comment by rbdubz3** [comment]
aarrggg - I'll try it out later - anyone every attempt to replace a hub? Any easy way to swap it out? I have about 30 bulbs and 12 or so Lightify Groups that I'd need to re-do :(

**Comment by duffrecords** [comment]
The gateway doesn't seem to have any means of backing up its configuration that I'm aware of.  I've had to redo my entire setup more than once due to light/group data inexplicably disappearing or residual "phantom" devices apparently causing naming conflicts.  I feel your pain.  It takes forever to factory reset that many devices and painstakingly recreate the groups in the app.

**Pull request merged**
